# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dc3c65927eebc351d9401c7b5e37754f594ac8cc7897cd3e76ee681769c28822f2866a64f860ccbe4b5fdaa70fcd5e4b4481db2b5652361f9f1e1a2c65453cc

test:
  secret_key_base: a24f7b796af18bbd604402c5617c4873d2b353477b4d4cb0de421acc1f2bbe79250d122015876af6de77ba431163fe67202e3a5340f8f7a64a9ec914bffde025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
